services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: localservicehub_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/localservicehub_development
      - REDIS_URL=redis://redis:6379/0
      - RAILS_MASTER_KEY
    volumes:
      - .:/rails
      - ruby_bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  redis_data:
  ruby_bundle_cache:
  node_modules: