# This file provides development-specific overrides
# Automatically loaded by docker-compose

services:
  web:
    # Override for development-specific settings
    environment:
      - RAILS_LOG_LEVEL=debug
      - RAILS_SERVE_STATIC_FILES=true
    # For faster development iteration, you could mount source code:
    # volumes:
    #   - .:/rails
    #   - bundle_cache:/usr/local/bundle
    
# Uncomment for development source code mounting
# volumes:
#   bundle_cache: