production:
  review_follow_up:
    class: ReviewFollowUpJob
    queue: default
    schedule: every day at 10am

development:
  review_follow_up:
    class: ReviewFollowUpJob
    queue: default
    schedule: every day at 10am
